/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccountTypes: () => import('#controllers/account_types_controller'),
  Accounts: () => import('#controllers/accounts_controller'),
  BudgetCategories: () => import('#controllers/budget_categories_controller'),
  Budgets: () => import('#controllers/budgets_controller'),
  Categories: () => import('#controllers/categories_controller'),
  CategoryGroups: () => import('#controllers/category_groups_controller'),
  CreditCardInstallments: () => import('#controllers/credit_card_installments_controller'),
  CreditCardInvoicePayments: () => import('#controllers/credit_card_invoice_payments_controller'),
  CreditCardInvoices: () => import('#controllers/credit_card_invoices_controller'),
  CreditCardPurchases: () => import('#controllers/credit_card_purchases_controller'),
  CreditCards: () => import('#controllers/credit_cards_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Payees: () => import('#controllers/payees_controller'),
  Profile: () => import('#controllers/profile_controller'),
  PurchaseItems: () => import('#controllers/purchase_items_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  RecurringTransactions: () => import('#controllers/recurring_transactions_controller'),
  Session: () => import('#controllers/session_controller'),
  Settings: () => import('#controllers/settings_controller'),
  ShoppingListItems: () => import('#controllers/shopping_list_items_controller'),
  ShoppingLists: () => import('#controllers/shopping_lists_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Transfers: () => import('#controllers/transfers_controller'),
}
