/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = AccountTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AccountSchema extends BaseModel {
  static $columns = ['accountTypeId', 'archived', 'archivedAt', 'color', 'createdAt', 'currency', 'currentBalanceCents', 'description', 'icon', 'id', 'initialBalanceCents', 'name', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accountTypeId: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare currentBalanceCents: number
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare initialBalanceCents: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class BudgetCategorySchema extends BaseModel {
  static $columns = ['assignedAmountCents', 'budgetId', 'categoryId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = BudgetCategorySchema.$columns
  @column()
  declare assignedAmountCents: number | null
  @column()
  declare budgetId: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BudgetSchema extends BaseModel {
  static $columns = ['alertPercentage', 'amountCents', 'archived', 'archivedAt', 'createdAt', 'description', 'endDate', 'id', 'name', 'periodType', 'startDate', 'status', 'updatedAt', 'userId'] as const
  $columns = BudgetSchema.$columns
  @column()
  declare alertPercentage: number | null
  @column()
  declare amountCents: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare periodType: string
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CategorySchema extends BaseModel {
  static $columns = ['archived', 'archivedAt', 'categoryGroupId', 'color', 'createdAt', 'description', 'icon', 'id', 'name', 'parentId', 'sortOrder', 'type', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare categoryGroupId: number
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CategoryGroupSchema extends BaseModel {
  static $columns = ['archived', 'archivedAt', 'color', 'createdAt', 'description', 'icon', 'id', 'name', 'sortOrder', 'type', 'updatedAt', 'userId'] as const
  $columns = CategoryGroupSchema.$columns
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CreditCardInstallmentSchema extends BaseModel {
  static $columns = ['amountCents', 'createdAt', 'creditCardInvoiceId', 'creditCardPurchaseId', 'dueDate', 'id', 'installmentNumber', 'status', 'totalInstallments', 'updatedAt', 'userId'] as const
  $columns = CreditCardInstallmentSchema.$columns
  @column()
  declare amountCents: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditCardInvoiceId: number | null
  @column()
  declare creditCardPurchaseId: number
  @column.date()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installmentNumber: number
  @column()
  declare status: string
  @column()
  declare totalInstallments: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CreditCardInvoicePaymentSchema extends BaseModel {
  static $columns = ['accountId', 'amountCents', 'createdAt', 'creditCardInvoiceId', 'id', 'notes', 'paymentDate', 'transactionId', 'updatedAt', 'userId'] as const
  $columns = CreditCardInvoicePaymentSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare amountCents: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditCardInvoiceId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare paymentDate: DateTime
  @column()
  declare transactionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CreditCardInvoiceSchema extends BaseModel {
  static $columns = ['closedAt', 'closingDate', 'createdAt', 'creditCardId', 'dueDate', 'id', 'openingDate', 'paidAmountCents', 'paidAt', 'referenceMonth', 'referenceYear', 'status', 'totalAmountCents', 'updatedAt', 'userId'] as const
  $columns = CreditCardInvoiceSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.date()
  declare closingDate: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditCardId: number
  @column.date()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare openingDate: DateTime
  @column()
  declare paidAmountCents: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare referenceMonth: number
  @column()
  declare referenceYear: number
  @column()
  declare status: string
  @column()
  declare totalAmountCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CreditCardPurchaseSchema extends BaseModel {
  static $columns = ['amountCents', 'archived', 'archivedAt', 'categoryId', 'createdAt', 'creditCardId', 'creditCardInvoiceId', 'description', 'id', 'installmentsCount', 'notes', 'payeeId', 'purchaseDate', 'status', 'updatedAt', 'userId'] as const
  $columns = CreditCardPurchaseSchema.$columns
  @column()
  declare amountCents: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditCardId: number
  @column()
  declare creditCardInvoiceId: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installmentsCount: number
  @column()
  declare notes: string | null
  @column()
  declare payeeId: number | null
  @column.date()
  declare purchaseDate: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CreditCardSchema extends BaseModel {
  static $columns = ['accountId', 'archived', 'archivedAt', 'brand', 'closingDay', 'color', 'createdAt', 'creditLimitCents', 'dueDay', 'icon', 'id', 'lastFourDigits', 'name', 'updatedAt', 'userId'] as const
  $columns = CreditCardSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare brand: string | null
  @column()
  declare closingDay: number
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditLimitCents: number
  @column()
  declare dueDay: number
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastFourDigits: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class PayeeSchema extends BaseModel {
  static $columns = ['archived', 'archivedAt', 'createdAt', 'document', 'email', 'id', 'name', 'notes', 'phone', 'updatedAt', 'userId'] as const
  $columns = PayeeSchema.$columns
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class PurchaseItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'notes', 'purchaseId', 'quantity', 'totalPriceCents', 'unit', 'unitPriceCents', 'updatedAt'] as const
  $columns = PurchaseItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare purchaseId: number
  @column()
  declare quantity: string | null
  @column()
  declare totalPriceCents: number | null
  @column()
  declare unit: string | null
  @column()
  declare unitPriceCents: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseSchema extends BaseModel {
  static $columns = ['accountId', 'archived', 'archivedAt', 'categoryId', 'createdAt', 'description', 'id', 'notes', 'payeeId', 'paymentMethod', 'purchaseDate', 'shoppingListId', 'totalAmountCents', 'transactionId', 'updatedAt', 'userId'] as const
  $columns = PurchaseSchema.$columns
  @column()
  declare accountId: number | null
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare payeeId: number | null
  @column()
  declare paymentMethod: string | null
  @column.date()
  declare purchaseDate: DateTime
  @column()
  declare shoppingListId: number | null
  @column()
  declare totalAmountCents: number
  @column()
  declare transactionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class RecurringTransactionSchema extends BaseModel {
  static $columns = ['accountId', 'amountCents', 'archived', 'archivedAt', 'autoCreate', 'categoryId', 'createdAt', 'description', 'endDate', 'frequency', 'id', 'interval', 'lastGeneratedAt', 'nextOccurrenceDate', 'notes', 'payeeId', 'startDate', 'status', 'type', 'updatedAt', 'userId'] as const
  $columns = RecurringTransactionSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare amountCents: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare autoCreate: boolean
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare interval: number
  @column.dateTime()
  declare lastGeneratedAt: DateTime | null
  @column.date()
  declare nextOccurrenceDate: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare payeeId: number | null
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'fiscalYearStartDay', 'fiscalYearStartMonth', 'id', 'locale', 'updatedAt', 'userId'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare fiscalYearStartDay: number
  @column()
  declare fiscalYearStartMonth: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class ShoppingListItemSchema extends BaseModel {
  static $columns = ['checked', 'createdAt', 'estimatedPriceCents', 'id', 'name', 'notes', 'quantity', 'shoppingListId', 'sortOrder', 'unit', 'updatedAt'] as const
  $columns = ShoppingListItemSchema.$columns
  @column()
  declare checked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estimatedPriceCents: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare quantity: string | null
  @column()
  declare shoppingListId: number
  @column()
  declare sortOrder: number
  @column()
  declare unit: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShoppingListSchema extends BaseModel {
  static $columns = ['archived', 'archivedAt', 'createdAt', 'description', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = ShoppingListSchema.$columns
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class TransactionSchema extends BaseModel {
  static $columns = ['accountId', 'amountCents', 'archived', 'archivedAt', 'categoryId', 'createdAt', 'description', 'dueDate', 'id', 'notes', 'paidAt', 'payeeId', 'paymentMethod', 'reference', 'status', 'transactionDate', 'type', 'updatedAt', 'userId'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare amountCents: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare payeeId: number | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare reference: string | null
  @column()
  declare status: string
  @column.date()
  declare transactionDate: DateTime
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class TransferSchema extends BaseModel {
  static $columns = ['amountCents', 'archived', 'archivedAt', 'createdAt', 'description', 'destinationAccountId', 'destinationTransactionId', 'id', 'notes', 'sourceAccountId', 'sourceTransactionId', 'status', 'transferDate', 'updatedAt', 'userId'] as const
  $columns = TransferSchema.$columns
  @column()
  declare amountCents: number
  @column()
  declare archived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare destinationAccountId: number
  @column()
  declare destinationTransactionId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare sourceAccountId: number
  @column()
  declare sourceTransactionId: number
  @column()
  declare status: string
  @column.date()
  declare transferDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
