import { DomainError as DomainLayerError } from '@repo/domain';
import { DomainError } from './errors.js';

const DOMAIN_HTTP_STATUS: Record<string, number> = {
  INVALID_CREDENTIALS: 401,
  USER_NOT_FOUND: 404,
  USER_EMAIL_CONFLICT: 409,
  ACCOUNT_TYPE_CONFLICT: 409,
  ACCOUNT_TYPE_NOT_FOUND: 404,
  TRANSACTION_INVALID_AMOUNT: 400,
  TRANSFER_INVALID_AMOUNT: 400,
  TRANSFER_SAME_ACCOUNT: 400,
  CREDIT_CARD_STATEMENT_PAYMENT_INVALID_AMOUNT: 400,
  CREDIT_CARD_STATEMENT_PAYMENT_ERROR: 400,
  CREDIT_CARD_PURCHASE_INVALID_TOTAL_AMOUNT: 400,
  CREDIT_CARD_PURCHASE_INVALID_INSTALLMENT_COUNT: 400,
  CREDIT_CARD_PURCHASE_INSTALLMENT_COUNT_MISMATCH: 400,
  CREDIT_CARD_PURCHASE_INSTALLMENT_SUM_MISMATCH: 400,
  CREDIT_CARD_PURCHASE_CREATE_ERROR: 400,
  ACCOUNT_NOT_FOUND: 404,
  CATEGORY_NOT_FOUND: 404,
  CATEGORY_GROUP_NOT_FOUND: 404,
  PAYEE_NOT_FOUND: 404,
  RECURRING_TRANSACTION_NOT_FOUND: 404,
  USER_SETTINGS_NOT_FOUND: 404,
  CREDIT_CARD_NOT_FOUND: 404,
  CREDIT_CARD_INSTALLMENT_NOT_FOUND: 404,
  CREDIT_CARD_STATEMENT_PAYMENT_NOT_FOUND: 404,
  STATEMENT_BALANCE_NOT_FOUND: 404,
};

export const mapDomainError = (error: unknown): never => {
  if (error instanceof DomainLayerError) {
    const domainError = error;
    const status = DOMAIN_HTTP_STATUS[domainError.code] ?? 400;

    throw new DomainError(status as 400 | 401 | 403 | 404 | 409, {
      code: domainError.code,
      message: domainError.message,
    });
  }

  throw error;
};
